POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "Test product",
    "price": 100
}

###
GET http://localhost:8000/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTYwNzg3MzQsInN1YiI6IjNjOTQ4ODI2LWIyNGQtNGMzYi05ODYwLWQ0MmRlOTdjY2NiNyJ9.wIIapHG69VNpfpGRAmQADlruBY6nAuAukPh-bHWxjcU
###
GET http://localhost:8000/products/f0699d63-4142-4cfe-a3fa-16778fdb59ab HTTP/1.1

###
GET http://localhost:8000/products?page=1&limit=10&sort=name HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:8000/products/f0699d63-4142-4cfe-a3fa-16778fdb59ab HTTP/1.1
Content-Type: application/json

{
    "name": "Updated product",
    "price": 150
}

###
DELETE http://localhost:8000/products/f0699d63-4142-4cfe-a3fa-16778fdb59ab HTTP/1.1